### ISSUE TITLE
Error in execution

### ISSUE THREAD

**Issue by PieDema96** [geojames/py_offNadir_Res#3]
When running the script recieve the following error.

Traceback (most recent call last):
  File "py_offNadir_Res_v1-0.py", line 310, in <module>
    main()
  File "py_offNadir_Res_v1-0.py", line 295, in main
    graphics(sensor,ifov)
  File "py_offNadir_Res_v1-0.py", line 186, in graphics
    fov = np.array([[0, sensor.flyH], [path.vertices[0][1], 0], [path.vertices[1][1], 0]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.

Do you have any idea if it is my fault? Here my inputs:
P_expl,22.42,52.0,71.0,3072,4096,300000,30

**Comment by geojames** [comment]
@PieDema96 The flying height of 300,000 meters is not going to work in this framework - that is in the satellite orbit altitude range. At that altitude the Earth's curvature come into play for resolution and field of view calculations. The original code was designed for UAS or low-altitude plane flights of 10m to maybe 1000 m and it treats the ground as a flat plane (no curvature) for the field of view/resolution calculations. 

It's failing in the graphic call because it cannot draw the shapes that big...

From your inputs I was able to get the outputs bypassing the graphics function - At this scale, I would not trust the outputs.

> Resolution Calculations Report
> 
> Camera Type:	P_expl
> Focal Length (mm):	22.42
> 
> Resolutions calculated for...
> Flying Height (m):	300000.0
> Off-nadir Angle(deg):	30.00
> 
> The IFOV covers:
> 	37714336268560.71 sq. meters / 3771433626.86 ha / 37714336.27 sq km
> 
> The IFOV pixel resolutions (m | cm)...
> Near Field =	136.633 | 13663.26
> Mid Field  =	261.539 | 26153.94
> Far Field  =	3047.564 | 304756.37
